# Site settings
title: Monoport
email: hi@monoport.hu
phone: +36-30-821-4589
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/mp/" # the subpath of your site, e.g. /blog/
url: "https://vestalux.github.io" # the base hostname & protocol for your site

facebook_username: monoport
github_username:

# Build settings
markdown: kramdown

collections:
  portfolio:
    output: true
    permalink: portfolio/:title/
